"""Fixed points system

Revision ID: 4e39768d5535
Revises: acdbf711369d
Create Date: 2025-10-05 17:19:19.316452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e39768d5535'
down_revision = 'acdbf711369d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_name', sa.String(length=255), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('security_question')
        batch_op.drop_column('security_answer_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_answer_hash', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('location')
        batch_op.drop_column('status')

    op.drop_table('reward_redemption')
    # ### end Alembic commands ###
